application:
  name: backend
  version: 1

  server:
    port: 3300
    idle-timeout: 5
    shutdown-timeout: 3

  db:
    host: localhost
    port: 54320
    name: test
    tls-enabled: false
    user:
      login: ???
      password: ???

  logger:
    level: info
    development: false
    encoding: json
    outputPaths: [ "stdout", "logs/app.log" ]
    errorOutputPaths: [ "stderr" ]
    encoderConfig:
      timeKey: ts
      levelKey: level
      messageKey: msg
      timeEncoder: iso8601
      levelEncoder: lowercase
      callerEncoder: none