application:
  name: pinger
  version: 1

  pinger:
    ping-period: 10
    request-timeout: 3
    worker-pool: 3

  docker:
    host: "unix:///var/run/docker.sock"

  consumer-server:
    host: "http://nginx:80/api/v1"
    max-retries: 5

  logger:
    level: info
    development: false
    encoding: json
    outputPaths: [ "stdout", "logs/app.log" ]
    errorOutputPaths: [ "stderr" ]
    encoderConfig:
      timeKey: ts
      levelKey: level
      messageKey: msg
      timeEncoder: iso8601
      levelEncoder: lowercase
      callerEncoder: none